### ISSUE TITLE
.Net Core 3.0 Not Logging to CloudWatch

### ISSUE THREAD

**Issue by firstdivision** [aws/aws-logging-dotnet#112]
I must be missing some simple configuration item somewhere that is preventing ASP.NET Core Logging from working.  This is what I have:

- Application is a .Net Core 3.0 Razor Pages app
- Deployed into AWS Fargate / Docker
- Razor Pages project has NuGet package AWS.Logger.AspNetCore 2.1.1 installed
- appsettings.json is confirmed to exist on the container running in fargate
- I have tried it with and without this line commented out `logging.SetMinimumLevel(LogLevel.Debug);`

The logs never appear in the CloudWatch `MyApplication.Web` Log groups section, but they do appear in the raw logs for the Fargate container itself:

![image](https://user-images.githubusercontent.com/6760828/70937329-b57ec500-2009-11ea-9a60-0bc4ed3fc4fe.png)

My guess would be IAM permissions on the task role, but I think the two that I have given it (`AmazonS3FullAccess`, `CloudWatchFullAccess`) should be more than sufficient.

Startup.cs:
```C#
public Startup(IWebHostEnvironment env)
{
    //set default culture so docker displays dollar signs right...
    CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("en-US");

    Configuration = new ConfigurationBuilder()
    .SetBasePath(env.ContentRootPath)
    .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
    .Build();

    HostingEnvironment = env;
}
```

appsettings.json:
```json
{
  "Logging": {
    "Region": "us-east-1",
    "LogGroup": "MyApplication.Web",
    "IncludeLogLevel": true,
    "IncludeCategory": true,
    "IncludeNewline": true,
    "IncludeException": true,
    "IncludeEventId": false,
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "AllowedHosts": "*"
}
```
Program.cs:
```C#
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
        .ConfigureLogging(logging => {
            logging.AddAWSProvider();

            // When you need logging below set the minimum level. Otherwise the logging framework will default to Informational for external providers.
            //logging.SetMinimumLevel(LogLevel.Debug);
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
}
```

The Fargate ECS Task Role has the following permissions:
AmazonS3FullAccess 
CloudWatchFullAccess 

I am injecting the logger instance into the Razor Pages classes:
```C#
public MyAccountModel(ILogger<MyAccountModel> logger, DataAccess.Models.DataContext db)
{
    this.logger = logger;
    this.db = db;
}
```

And then calling it:
```C#
public void OnGet()
{
    try
    {
        logger.LogError("This should appear in cloudwatch as an error.");
    }
    catch (Exception  ex)
    {
        logger.LogError(ex, "This should be an error that appears in cloudwatch");
    }
}
```

**Comment by adrianofo** [comment]
We are having the same issue.
Same config and code.

**Comment by firstdivision** [comment]
Any ideas on this?  Is it a .NET Core 3 thing or something else?

**Comment by jeansberg** [comment]
We also had this issue in our WebApi app. We seem to have solved it by removing the logging configuration code from Program.cs to ConfigureServices.
This is all we have at the moment:
`            services.AddLogging(logging =>
            {
                logging.AddAWSProvider(Configuration.GetAWSLoggingConfigSection());
                logging.SetMinimumLevel(LogLevel.Debug);
            });`

**Comment by firstdivision** [comment]
@jeansberg That got it working for me as well.

**Comment by normj** [comment]
Calling `logging.AddAWSProvider();` during the creation of the IHostBuilder in Program.cs assumes that the Configuration object is added the host's service collection. I believe in the `ASP.NET Core` project template it uses `ConfigureWebHostDefaults` in the `CreateHostBuilder` call which adds the Configuration object to the service collection.

**Comment by normj** [comment]
I have recreated the issue of logging not getting enabled from `CreateHostBuilder` and investigated what is going on.

**Comment by EstebanMellado** [comment]
In my case was the AWS Credentials Profile. I was using a custom profile, and then I created the "default" profile with my AWS user which has the CloudWatchFullAccess policy.

**Comment by Cular** [comment]
As I understand the problem is in `IConfiguration` registration in net core 3.1.
In aspnet core 2.2 `IConfiguration` in `IServiceCollection` was registered with `ImplementationInstance`
In aspnet core 3.1 `IConfiguration` in `IServiceCollection` has null `ImplementationInstance`

Decompile screenshots:
![netcore22](https://user-images.githubusercontent.com/26927442/75706483-f069ce00-5cc5-11ea-8c1f-6f06d5b96220.png)
![netcore31](https://user-images.githubusercontent.com/26927442/75706487-f3fd5500-5cc5-11ea-9898-f2fcdc8502dc.png)

As I see the problem was fixed:
https://github.com/aws/aws-logging-dotnet/commit/cbca17b1933cbd12cbe4fc10a1fbf80eb00f9ef1#diff-b735b5c6050ab5da15329da6a44aaa7c

@normj we are looking forward to a new version of library. Any estimations? =)

**Comment by normj** [comment]
I just pushed out new versions that fixes the .NET Core 3.1 registration issue.

**Comment by janaka** [comment]
@normj where did you push out a new version. The latest Nuget package is v2.2.0 from what I can see and I seem to be having this problem. Can you confirm if this fix is in AWS.Logger.AspNetCore v2.2.0? 

Thanks

**Comment by classifieds-dev** [comment]
I'm having the same issue. I've used a variety of different configurations. I have been able to populate the created log stream(s) with events. I've used the following configurations:

Default logger in aws-lambda-dotnet
.NET Core 3 logger in this package.
Serilog AWS sink.
The lambda which is being tested is associated with a role that has a policy containing permissions to read and write cloud watch log streams, and events. The role also can be assumed by the lambda service.

When the lambda is tested in the lambda testing console the log entries are written and clearly visible. However, the log entries are not being persisted to the associated cloud watch stream.

**Comment by mharrisn** [comment]
I'm still seeing this issue with version 2.2.0. If anyone has this working in a .Net core 3.1 Web API, can you please paste you implementation from appsettings.json, Program.cs , and Setup.cs?

**Comment by ashishdhingra** [comment]
Hi @firstdivision, 

Good afternoon.

Please confirm if this is still an issue or it could be closed.

Thanks,
Ashish

**Comment by abeardsley-vertex** [comment]
It's been working for me, so I think we can close this.  Thank you.

**Comment by firstdivision** [comment]
It's been working for me, so I think we can close this one.  Thank you.

**Comment by prcdpr** [comment]
For me it helped to set DisableLogGroupCreation to true
```
logging.AddAWSProvider(new AWSLoggerConfig
{
    // Or else we need additional permissions.
    DisableLogGroupCreation = true
});
```

It's because my logging group is created by CDK and service has only access to `logs:CreateLogStream`, `logs:PutLogEvents`.
But it doesn't have the access to `logs:DescribeLogGroups`, therefore logging wasn't working.

**Comment by kreditkenny** [comment]
i did this, and can't believe this worked. thanks @prcdpr !

**Comment by Sbolder** [comment]
Hi,
i'm sorry but i'have the same problem with dotnet6 and AWS.Logger.AspNetCore 3.3.0

I have configured this logging:

`
            services.AddLogging(config =>
            {
                config.AddAWSProvider(configuration.GetAWSLoggingConfigSection());
                config.SetMinimumLevel(LogLevel.Debug);
            });`

appsettings.json

`  "Logging": {
    "Region": "eu-west-2",
    "LogGroup": "TEST.Logging.EKS"
  },`

in local env this work done, the log is written on cloudwatch logGroup correctly.

But in EKS FARGATE deploy this dosn't work, any error is logged, and my cluster have full access on cloudwatch resource.

on kubernetes i have overwrite this property with env variable:

`            - name: Logging__Region
              value: eu-west-2
            - name: Logging__LogGroup
              value: TEST.Logging.EKS10`

Anyone could help me to find a problem or trubleshooting it?

Thank you.

**Comment by 4saken07** [comment]
Had the same issue on Net 8 + Fargate. ECS logs would work but structured apps logs would not. Locally this ALWAYS worked. Using minimal API in `program.cs`

Changing this

```
builder.Logging
    .AddAWSProvider()
    .SetMinimumLevel(LogLevel.Information);
```

to this

```
builder.Services.AddLogging(logging =>
{
    logging.AddAWSProvider();
    logging.SetMinimumLevel(LogLevel.Debug);
});
```

worked and the log group was created and logged to
